#requires built images:
#from markowitzpy directory run:
#docker build -t img_markowitz .

#access to bash on python_ml container:
#docker exec -it python_ml bash

version: '3'
services:
  markowitz:
    image: gcr.io/expanded-run-177512/img_markowitz:latest
    ports:
     - "5000:5000"
    container_name: markowitz-cont
    stdin_open: true
    environment:
      PGPASSWORD: postgres
      PGHOST: postgres_ml
      FLASK_APP: webapp.py
    tty: true
#    links:
#      - db
    working_dir: /usr/src/app
#    volumes:
#      - ${HOME}/dev/markowitzpy:/usr/src/app
    command:
      python -m flask run --host=0.0.0.0
