#requires built images:
#from dockerdm directory run:
#docker build -t ml_python python/
#docker build -t ml_postgresql postgres/
#docker build -t img_markowitz markowitz/

#access to bash on python_ml container:
#docker exec -it python_ml bash

version: '3'
volumes:
  # We'll define a volume that will store the data from the postgres databases:
  postgres-data:
    driver: local
services:
  db:
    restart: always
    image: ml_postgresql:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      DB_HOST: postgres
    ports:
      - 5432:5432
    container_name: postgres_ml
    volumes:
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      #- postgres-data:/var/lib/postgresql/data
      - ${HOME}/dev:/mnt/dev
      - ${HOME}/dev/postgresdata:/var/lib/postgresql/data
  python:
    image: ml_python:latest
    container_name: python_ml
    stdin_open: true
    environment:
      PGPASSWORD: postgres
      PGHOST: postgres_ml
    tty: true
    links:
      - db
    ports:
      - "49100:22"
    volumes:
      - ${HOME}/dev:/mnt/dev
#    command: bash -c /usr/sbin/sshd", "-D"
#    command: bash -c "/etc/init.d/postfix restart && /usr/sbin/sshd -D"
  markowitz:
    image: img_markowitz:latest
    container_name: markowitz_cont
    stdin_open: true
    environment:
      PGPASSWORD: postgres
      PGHOST: postgres_ml
    tty: true
    links:
      - db
    volumes:
      - ${HOME}/dev:/mnt/dev
    command:
      bash
