apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /home/ben/dev/dockerdm/docker-compose-mark-gcloud.yml
      convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
