apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: internal
    kompose.cmd: kompose -f /home/ben/dev/dockerdm/docker-compose-mark-gcloud.yml
      up
    kompose.service.type: LoadBalancer
    kompose.version: 1.1.0 (36652f6)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"kompose -f /home/ben/dev/dockerdm/docker-compose-mark-gcloud.yml up","kompose.service.type":"LoadBalancer","kompose.version":"1.1.0 (36652f6)"},"creationTimestamp":null,"labels":{"io.kompose.service":"frontend"},"name":"frontend","namespace":"default","selfLink":"/api/v1/namespaces/default/services/frontend"},"spec":{"externalTrafficPolicy":"Cluster","loadBalancerIP":"104.197.156.69","ports":[{"name":"80","nodePort":31458,"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"io.kompose.service":"frontend"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  selfLink: /api/v1/namespaces/default/services/frontend
spec:
#  clusterIP: <unknown>
  externalTrafficPolicy: Cluster
  loadBalancerIP: 104.154.186.27
  ports:
  - name: "80"
    nodePort: 31458
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
